library(testthat)

####### e_value
result <- e_value(stats::rnorm(10), forecast_input(mu = stats::rnorm(10), sd = 1), forecast_input(mu = -stats::rnorm(10), sd = 1), method = c("alt-cons","GRAPA", "lambda", "alt-conf", "alt-more-cons"), p.value.method = "t")
test_that("test e_value does return evalue", { expect_type(result, "list") })
test_that("test e_value does return evalue - length y", { expect_equal(length(result$y), 10) })
test_that("test e_value does return evalue - crps.F length", { expect_equal(length(result$crps.F), 10) })
test_that("test e_value does return evalue - crps.F.para length", { expect_equal(length(result$crps.F.para), 7) })
test_that("test e_value does return evalue - crps.F.para - length mu", { expect_equal(length(result$crps.F.para$mu), 10) })
test_that("test e_value does return evalue - crps.F.para - length sd", { expect_equal(length(result$crps.F.para$sd), 1) })
test_that("test e_value does return evalue - crps.F.para types - fun", { expect_type(result$crps.F.para$fun, "closure") })
test_that("test e_value does return evalue - crps.F.para types - crps.fun.y.matrix", { expect_type(result$crps.F.para$crps.fun.y.matrix, "closure") })
test_that("test e_value does return evalue - crps.F.para types - sample.fun", { expect_type(result$crps.F.para$sample.fun, "closure") })
test_that("test e_value does return evalue - crps.F.para types - inf.fun", { expect_type(result$crps.F.para$inf.fun, "closure") })
test_that("test e_value does return evalue - crps.F.para - method", { expect_equal(result$crps.F.para$method, "norm") })
test_that("test e_value does return evalue - crps.G.para length", { expect_equal(length(result$crps.G.para), 7) })
test_that("test e_value does return evalue - crps.G length", { expect_equal(length(result$crps.G), 10) })
test_that("test e_value does return evalue - crps.G.para - length mu", { expect_equal(length(result$crps.G.para$mu), 10) })
test_that("test e_value does return evalue - crps.G.para - length sd", { expect_equal(length(result$crps.G.para$sd), 1) })
test_that("test e_value does return evalue - crps.G.para types - fun", { expect_type(result$crps.G.para$fun, "closure") })
test_that("test e_value does return evalue - crps.G.para types - crps.fun.y.matrix", { expect_type(result$crps.G.para$crps.fun.y.matrix, "closure") })
test_that("test e_value does return evalue - crps.G.para types - sample.fun", { expect_type(result$crps.G.para$sample.fun, "closure") })
test_that("test e_value does return evalue - crps.G.para types - inf.fun", { expect_type(result$crps.G.para$inf.fun, "closure") })
test_that("test e_value does return evalue - crps.G.para - method", { expect_equal(result$crps.G.para$method, "norm") })
test_that("test e_value does return evalue - inf.crps type", { expect_type(result$inf.crps, "double") })
test_that("test e_value does return evalue - method", { expect_equal(result$method, c("alt-cons","GRAPA", "lambda", "alt-conf", "alt-more-cons")) })
test_that("test e_value does return evalue - p.value.method", { expect_equal(result$p.value.method, "t") })
test_that("test e_value does return evalue - p.value", { expect_equal(length(result$p.value), 1) })
test_that("test e_value does return evalue - crps.alt.cons", { expect_true(is.matrix(result$crps.alt.cons)) })
test_that("test e_value does return evalue - e.value.alt.cons", { expect_equal(length(result$e.value.alt.cons), 10) })
test_that("test e_value does return evalue - lambda.alt.cons", { expect_equal(length(result$lambda.alt.cons), 10) })
test_that("test e_value does return evalue - e.value.alt.cons.prod", { expect_equal(length(result$e.value.alt.cons.prod), 1) })
test_that("test e_value does return evalue - e.value.alt.cons.prod - type", { expect_type(result$e.value.alt.cons.prod, "double") })
test_that("test e_value does return evalue - crps.alt.conf", { expect_true(is.matrix(result$crps.alt.conf)) })
test_that("test e_value does return evalue - e.value.alt.conf", { expect_equal(length(result$e.value.alt.conf), 10) })
test_that("test e_value does return evalue - lambda.alt.conf", { expect_equal(length(result$lambda.alt.conf), 10) })
test_that("test e_value does return evalue - e.value.alt.conf.prod", { expect_equal(length(result$e.value.alt.conf.prod), 1) })
test_that("test e_value does return evalue - e.value.alt.conf.prod - type", { expect_type(result$e.value.alt.conf.prod, "double") })
test_that("test e_value does return evalue - crps.alt.more.cons", { expect_true(is.matrix(result$crps.alt.more.cons)) })
test_that("test e_value does return evalue - e.value.alt.more.cons", { expect_equal(length(result$e.value.alt.more.cons), 10) })
test_that("test e_value does return evalue - lambda.alt.more.cons", { expect_equal(length(result$lambda.alt.more.cons), 10) })
test_that("test e_value does return evalue - e.value.alt.more.cons.prod", { expect_equal(length(result$e.value.alt.more.cons.prod), 1) })
test_that("test e_value does return evalue - e.value.alt.more.cons.prod - type", { expect_type(result$e.value.alt.more.cons.prod, "double") })

result.p.value.dm <- e_value(stats::rnorm(10), forecast_input(mu = stats::rnorm(10), sd = 1), forecast_input(mu = -stats::rnorm(10), sd = 1), method = c("alt-cons","GRAPA", "lambda", "alt-conf", "alt-more-cons"), p.value.method = "dm")
test_that("test p_value does return pvalue", { expect_type(result.p.value.dm, "list") })
test_that("test p_value does return pvalue - p.value length", { expect_equal(length(result.p.value.dm$p.value), 1) })
test_that("test p_value does return pvalue - p.value.method", { expect_equal(result.p.value.dm$p.value.method, "dm") })

# mixnorm
mu <- stats::rnorm(10)
tau <- sample(c(-1, 1), 10, replace = TRUE)
result.mixnorm <- e_value(stats::rnorm(10), forecast_input(mu = mu, sd = 1), forecast_input(mu = cbind(mu, mu + tau), sd = matrix(nrow = 10, ncol = 2, 1), w = matrix(nrow = 10, ncol = 2, 1 / 2)), method = c("alt-cons","GRAPA", "lambda", "alt-conf", "alt-more-cons"), p.value.method = "t")
test_that("test e_value does return evalue for mixnorm", { expect_type(result.mixnorm, "list") })
test_that("test e_value does return evalue for mixnorm - length y", { expect_equal(length(result.mixnorm$y), 10) })
test_that("test e_value does return evalue for mixnorm - crps.F length", { expect_equal(length(result.mixnorm$crps.F), 10) })
test_that("test e_value does return evalue for mixnorm - crps.F.para length", { expect_equal(length(result.mixnorm$crps.F.para), 7) })
test_that("test e_value does return evalue for mixnorm - crps.F.para - length mu", { expect_equal(length(result.mixnorm$crps.F.para$mu), 10) })
test_that("test e_value does return evalue for mixnorm - crps.F.para - length sd", { expect_equal(length(result.mixnorm$crps.F.para$sd), 1) })
test_that("test e_value does return evalue for mixnorm - crps.F.para types - fun", { expect_type(result.mixnorm$crps.F.para$fun, "closure") })
test_that("test e_value does return evalue for mixnorm - crps.F.para types - crps.fun.y.matrix", { expect_type(result.mixnorm$crps.F.para$crps.fun.y.matrix, "closure") })
test_that("test e_value does return evalue for mixnorm - crps.F.para types - sample.fun", { expect_type(result.mixnorm$crps.F.para$sample.fun, "closure") })
test_that("test e_value does return evalue for mixnorm - crps.F.para types - inf.fun", { expect_type(result.mixnorm$crps.F.para$inf.fun, "closure") })
test_that("test e_value does return evalue for mixnorm - crps.F.para - method", { expect_equal(result.mixnorm$crps.F.para$method, "norm") })
test_that("test e_value does return evalue for mixnorm - crps.G.para length", { expect_equal(length(result.mixnorm$crps.G.para), 8) })
test_that("test e_value does return evalue for mixnorm - crps.G length", { expect_equal(length(result.mixnorm$crps.G), 10) })
test_that("test e_value does return evalue for mixnorm - crps.G.para - dim mu", { expect_equal(dim(result.mixnorm$crps.G.para$mu), c(10, 2)) })
test_that("test e_value does return evalue for mixnorm - crps.G.para - dim sd", { expect_equal(dim(result.mixnorm$crps.G.para$sd), c(10,2)) })
test_that("test e_value does return evalue for mixnorm - crps.G.para - dim w", { expect_equal(dim(result.mixnorm$crps.G.para$w), c(10,2)) })
test_that("test e_value does return evalue for mixnorm - crps.G.para types - fun", { expect_type(result.mixnorm$crps.G.para$fun, "closure") })
test_that("test e_value does return evalue for mixnorm - crps.G.para types - crps.fun.y.matrix", { expect_type(result.mixnorm$crps.G.para$crps.fun.y.matrix, "closure") })
test_that("test e_value does return evalue for mixnorm - crps.G.para types - sample.fun", { expect_type(result.mixnorm$crps.G.para$sample.fun, "closure") })
test_that("test e_value does return evalue for mixnorm - crps.G.para types - inf.fun", { expect_type(result.mixnorm$crps.G.para$inf.fun, "closure") })
test_that("test e_value does return evalue for mixnorm - crps.G.para - method", { expect_equal(result.mixnorm$crps.G.para$method, "mixnorm") })
test_that("test e_value does return evalue for mixnorm - inf.crps type", { expect_type(result.mixnorm$inf.crps, "double") })
test_that("test e_value does return evalue for mixnorm - method", { expect_equal(result.mixnorm$method, c("alt-cons","GRAPA", "lambda", "alt-conf", "alt-more-cons")) })
test_that("test e_value does return evalue for mixnorm - p.value.method", { expect_equal(result.mixnorm$p.value.method, "t") })
test_that("test e_value does return evalue for mixnorm - p.value", { expect_equal(length(result.mixnorm$p.value), 1) })
test_that("test e_value does return evalue for mixnorm - crps.alt.cons", { expect_true(is.matrix(result.mixnorm$crps.alt.cons)) })
test_that("test e_value does return evalue for mixnorm - e.value.alt.cons", { expect_equal(length(result.mixnorm$e.value.alt.cons), 10) })
test_that("test e_value does return evalue for mixnorm - lambda.alt.cons", { expect_equal(length(result.mixnorm$lambda.alt.cons), 10) })
test_that("test e_value does return evalue for mixnorm - e.value.alt.cons.prod", { expect_equal(length(result.mixnorm$e.value.alt.cons.prod), 1) })
test_that("test e_value does return evalue for mixnorm - e.value.alt.cons.prod - type", { expect_type(result.mixnorm$e.value.alt.cons.prod, "double") })
test_that("test e_value does return evalue for mixnorm - crps.alt.conf", { expect_true(is.matrix(result$crps.alt.conf)) })
test_that("test e_value does return evalue for mixnorm - e.value.alt.conf", { expect_equal(length(result$e.value.alt.conf), 10) })
test_that("test e_value does return evalue for mixnorm - lambda.alt.conf", { expect_equal(length(result$lambda.alt.conf), 10) })
test_that("test e_value does return evalue for mixnorm - e.value.alt.conf.prod", { expect_equal(length(result$e.value.alt.conf.prod), 1) })
test_that("test e_value does return evalue for mixnorm - e.value.alt.conf.prod - type", { expect_type(result$e.value.alt.conf.prod, "double") })
test_that("test e_value does return evalue for mixnorm - crps.alt.more.cons", { expect_true(is.matrix(result$crps.alt.more.cons)) })
test_that("test e_value does return evalue for mixnorm - e.value.alt.more.cons", { expect_equal(length(result$e.value.alt.more.cons), 10) })
test_that("test e_value does return evalue for mixnorm - lambda.alt.more.cons", { expect_equal(length(result$lambda.alt.more.cons), 10) })
test_that("test e_value does return evalue for mixnorm - e.value.alt.more.cons.prod", { expect_equal(length(result$e.value.alt.more.cons.prod), 1) })
test_that("test e_value does return evalue for mixnorm - e.value.alt.more.cons.prod - type", { expect_type(result$e.value.alt.more.cons.prod, "double") })

# mixnorm - climatologocial
mu <- stats::rnorm(10)
tau <- sample(c(-1, 1), 10, replace = TRUE)
result.clim.mixnorm <- e_value(rnorm(10), forecast_input(mu = 0, sd = 1), forecast_input(mu = cbind(mu, mu + tau), sd = matrix(nrow = 10, ncol = 2, 1), w = matrix(nrow = 10, ncol = 2, 1 / 2)), method = c("alt-cons","GRAPA", "lambda", "alt-conf", "alt-more-cons"), p.value.method = "t")
test_that("test e_value does return evalue for mixnorm and climatological", { expect_type(result.clim.mixnorm, "list") })

####### next_k_e_values
mu <- stats::rnorm(10)
y <- stats::rnorm(10, mu)
result.next.k.first <- e_value(y = y, crps.F.para = list("mu" = mu, "sd" = 1), crps.G.para = list("mu" = 0, "sd" = 2), method = c("alt-cons","GRAPA", "lambda", "alt-conf", "alt-more-cons"), p.value.method = "t")
new.mu <- stats::rnorm(1)
result.next.k <- e_value(old.run.e.value = result.next.k.first, new.y = stats::rnorm(1, new.mu), new.crps.F.para = list("mu" = new.mu, "sd" = NA), new.crps.G.para = list("mu" = NA, "sd" = NA))
test_that("next_k_e_values work as expected - dim crps.alt.cons", { expect_equal(dim(result.next.k$crps.alt.cons), c(11, 50)) })
test_that("next_k_e_values work as expected - length y", { expect_equal(length(result.next.k$y), 11) })
test_that("next_k_e_values work as expected - crps.F length", { expect_equal(length(result.next.k$crps.F), 11) })
test_that("next_k_e_values work as expected - crps.F.para length", { expect_equal(length(result.next.k$crps.F.para), 7) })
test_that("next_k_e_values work as expected - crps.F.para - length mu", { expect_equal(length(result.next.k$crps.F.para$mu), 11) })
test_that("next_k_e_values work as expected - crps.F.para - mu", { expect_equal(result.next.k$crps.F.para$mu, c(mu, new.mu)) })
test_that("next_k_e_values work as expected - crps.F.para - length sd", { expect_equal(length(result.next.k$crps.F.para$sd), 1) })
test_that("next_k_e_values work as expected - crps.F.para types - fun", { expect_type(result.next.k$crps.F.para$fun, "closure") })
test_that("next_k_e_values work as expected - crps.F.para types - crps.fun.y.matrix", { expect_type(result.next.k$crps.F.para$crps.fun.y.matrix, "closure") })
test_that("next_k_e_values work as expected - crps.F.para types - sample.fun", { expect_type(result.next.k$crps.F.para$sample.fun, "closure") })
test_that("next_k_e_values work as expected - crps.F.para types - inf.fun", { expect_type(result.next.k$crps.F.para$inf.fun, "closure") })
test_that("next_k_e_values work as expected - crps.F.para - method", { expect_equal(result.next.k$crps.F.para$method, "norm") })
test_that("next_k_e_values work as expected - crps.G.para length", { expect_equal(length(result.next.k$crps.G.para), 7) })
test_that("next_k_e_values work as expected - crps.G length", { expect_equal(length(result.next.k$crps.G), 11) })
test_that("next_k_e_values work as expected - crps.G.para - length mu", { expect_equal(length(result.next.k$crps.G.para$mu), 1) })
test_that("next_k_e_values work as expected - crps.G.para - length sd", { expect_equal(length(result.next.k$crps.G.para$sd), 1) })
test_that("next_k_e_values work as expected - crps.G.para types - fun", { expect_type(result.next.k$crps.G.para$fun, "closure") })
test_that("next_k_e_values work as expected - crps.G.para types - crps.fun.y.matrix", { expect_type(result.next.k$crps.G.para$crps.fun.y.matrix, "closure") })
test_that("next_k_e_values work as expected - crps.G.para types - sample.fun", { expect_type(result.next.k$crps.G.para$sample.fun, "closure") })
test_that("next_k_e_values work as expected - crps.G.para types - inf.fun", { expect_type(result.next.k$crps.G.para$inf.fun, "closure") })
test_that("next_k_e_values work as expected - crps.G.para - method", { expect_equal(result.next.k$crps.G.para$method, "norm") })
test_that("next_k_e_values work as expected - inf.crps type", { expect_type(result.next.k$inf.crps, "double") })
test_that("next_k_e_values work as expected - method", { expect_equal(result.next.k$method, c("alt-cons","GRAPA", "lambda", "alt-conf", "alt-more-cons")) })
test_that("next_k_e_values work as expected - p.value.method", { expect_equal(result.next.k$p.value.method, "t") })
test_that("next_k_e_values work as expected - p.value", { expect_equal(length(result.next.k$p.value), 1) })
test_that("next_k_e_values work as expected - crps.alt.cons", { expect_equal(dim(result.next.k$crps.alt.cons), c(11, 50)) })
test_that("next_k_e_values work as expected - e.value.alt.cons", { expect_equal(length(result.next.k$e.value.alt.cons), 11) })
test_that("next_k_e_values work as expected - lambda.alt.cons", { expect_equal(length(result.next.k$lambda.alt.cons), 11) })
test_that("next_k_e_values work as expected - e.value.alt.cons.prod", { expect_equal(length(result.next.k$e.value.alt.cons.prod), 1) })
test_that("next_k_e_values work as expected - e.value.alt.cons.prod - type", { expect_type(result.next.k$e.value.alt.cons.prod, "double") })
test_that("next_k_e_values work as expected - crps.alt.conf", { expect_true(is.matrix(result.next.k$crps.alt.conf)) })
test_that("next_k_e_values work as expected - e.value.alt.conf", { expect_equal(length(result.next.k$e.value.alt.conf), 11) })
test_that("next_k_e_values work as expected - lambda.alt.conf", { expect_equal(length(result.next.k$lambda.alt.conf), 11) })
test_that("next_k_e_values work as expected - e.value.alt.conf.prod", { expect_equal(length(result.next.k$e.value.alt.conf.prod), 1) })
test_that("next_k_e_values work as expected - e.value.alt.conf.prod - type", { expect_type(result.next.k$e.value.alt.conf.prod, "double") })
test_that("next_k_e_values work as expected - crps.alt.more.cons", { expect_true(is.matrix(result.next.k$crps.alt.more.cons)) })
test_that("next_k_e_values work as expected - e.value.alt.more.cons", { expect_equal(length(result.next.k$e.value.alt.more.cons), 11) })
test_that("next_k_e_values work as expected - lambda.alt.more.cons", { expect_equal(length(result.next.k$lambda.alt.more.cons), 11) })
test_that("next_k_e_values work as expected - e.value.alt.more.cons.prod", { expect_equal(length(result.next.k$e.value.alt.more.cons.prod), 1) })
test_that("next_k_e_values work as expected - e.value.alt.more.cons.prod - type", { expect_type(result.next.k$e.value.alt.more.cons.prod, "double") })

mu <- stats::rnorm(10)
tau <- sample(c(-1, 1), 10, replace = TRUE)
result.next.k.clim.mixnorm.first <- e_value(rnorm(10), forecast_input(mu = 0, sd = 1), forecast_input(mu = cbind(mu, mu + tau), sd = matrix(nrow = 10, ncol = 2, 1), w = matrix(nrow = 10, ncol = 2, 1 / 2)), method = c("alt-cons","GRAPA", "lambda", "alt-conf", "alt-more-cons"), p.value.method = "t")
new.mu <- stats::rnorm(1)
new.tau <- sample(c(-1, 1), 1)
result.next.k.clim.mixnorm <- e_value(old.run.e.value = result.next.k.clim.mixnorm.first, new.y = stats::rnorm(1, new.mu), new.crps.F.para = list("mu" = NA, "sd" = NA), new.crps.G.para = list("mu" = c(new.mu, new.mu + new.tau), "sd" = c(1,1), "w" = c(1/2, 1/2)))
test_that("next_k_e_values work as expected mixnorm - dim crps.alt.cons", { expect_equal(dim(result.next.k.clim.mixnorm$crps.alt.cons), c(11, 50)) })
test_that("next_k_e_values work as expected mixnorm - length y", { expect_equal(length(result.next.k.clim.mixnorm$y), 11) })
test_that("next_k_e_values work as expected mixnorm - crps.F length", { expect_equal(length(result.next.k.clim.mixnorm$crps.F), 11) })
test_that("next_k_e_values work as expected mixnorm - crps.F.para length", { expect_equal(length(result.next.k.clim.mixnorm$crps.F.para), 7) })
test_that("next_k_e_values work as expected mixnorm - crps.F.para - length mu", { expect_equal(length(result.next.k.clim.mixnorm$crps.F.para$mu), 1) })
test_that("next_k_e_values work as expected mixnorm - crps.F.para - length sd", { expect_equal(length(result.next.k.clim.mixnorm$crps.F.para$sd), 1) })
test_that("next_k_e_values work as expected mixnorm - crps.F.para types - fun", { expect_type(result.next.k.clim.mixnorm$crps.F.para$fun, "closure") })
test_that("next_k_e_values work as expected mixnorm - crps.F.para types - crps.fun.y.matrix", { expect_type(result.next.k.clim.mixnorm$crps.F.para$crps.fun.y.matrix, "closure") })
test_that("next_k_e_values work as expected mixnorm - crps.F.para types - sample.fun", { expect_type(result.next.k.clim.mixnorm$crps.F.para$sample.fun, "closure") })
test_that("next_k_e_values work as expected mixnorm - crps.F.para types - inf.fun", { expect_type(result.next.k.clim.mixnorm$crps.F.para$inf.fun, "closure") })
test_that("next_k_e_values work as expected mixnorm - crps.F.para - method", { expect_equal(result.next.k.clim.mixnorm$crps.F.para$method, "norm") })
test_that("next_k_e_values work as expected mixnorm - crps.G.para length", { expect_equal(length(result.next.k.clim.mixnorm$crps.G.para), 8) })
test_that("next_k_e_values work as expected mixnorm - crps.G length", { expect_equal(length(result.next.k.clim.mixnorm$crps.G), 11) })
test_that("next_k_e_values work as expected mixnorm - crps.G.para - mu matrix", { expect_true(is.matrix(result.next.k.clim.mixnorm$crps.G.para$mu)) })
test_that("next_k_e_values work as expected mixnorm - crps.G.para - mu dim", { expect_equal(dim(result.next.k.clim.mixnorm$crps.G.para$mu), c(11, 2)) })
test_that("next_k_e_values work as expected mixnorm - crps.G.para - sd matrix", { expect_true(is.matrix(result.next.k.clim.mixnorm$crps.G.para$sd)) })
test_that("next_k_e_values work as expected mixnorm - crps.G.para - sd dim", { expect_equal(dim(result.next.k.clim.mixnorm$crps.G.para$sd), c(11, 2)) })
test_that("next_k_e_values work as expected mixnorm - crps.G.para types - fun", { expect_type(result.next.k.clim.mixnorm$crps.G.para$fun, "closure") })
test_that("next_k_e_values work as expected mixnorm - crps.G.para types - crps.fun.y.matrix", { expect_type(result.next.k.clim.mixnorm$crps.G.para$crps.fun.y.matrix, "closure") })
test_that("next_k_e_values work as expected mixnorm - crps.G.para types - sample.fun", { expect_type(result.next.k.clim.mixnorm$crps.G.para$sample.fun, "closure") })
test_that("next_k_e_values work as expected mixnorm - crps.G.para types - inf.fun", { expect_type(result.next.k.clim.mixnorm$crps.G.para$inf.fun, "closure") })
test_that("next_k_e_values work as expected mixnorm - crps.G.para - method", { expect_equal(result.next.k.clim.mixnorm$crps.G.para$method, "mixnorm") })
test_that("next_k_e_values work as expected mixnorm - inf.crps type", { expect_type(result.next.k.clim.mixnorm$inf.crps, "double") })
test_that("next_k_e_values work as expected mixnorm - method", { expect_equal(result.next.k.clim.mixnorm$method, c("alt-cons","GRAPA", "lambda", "alt-conf", "alt-more-cons")) })
test_that("next_k_e_values work as expected mixnorm - p.value.method", { expect_equal(result.next.k.clim.mixnorm$p.value.method, "t") })
test_that("next_k_e_values work as expected mixnorm - p.value", { expect_equal(length(result.next.k.clim.mixnorm$p.value), 1) })
test_that("next_k_e_values work as expected mixnorm - crps.alt.cons", { expect_equal(dim(result.next.k.clim.mixnorm$crps.alt.cons), c(11, 50)) })
test_that("next_k_e_values work as expected mixnorm - e.value.alt.cons", { expect_equal(length(result.next.k.clim.mixnorm$e.value.alt.cons), 11) })
test_that("next_k_e_values work as expected mixnorm - lambda.alt.cons", { expect_equal(length(result.next.k.clim.mixnorm$lambda.alt.cons), 11) })
test_that("next_k_e_values work as expected mixnorm - e.value.alt.cons.prod", { expect_equal(length(result.next.k.clim.mixnorm$e.value.alt.cons.prod), 1) })
test_that("next_k_e_values work as expected mixnorm - e.value.alt.cons.prod - type", { expect_type(result.next.k.clim.mixnorm$e.value.alt.cons.prod, "double") })
test_that("next_k_e_values work as expected mixnorm - crps.alt.conf", { expect_true(is.matrix(result.next.k.clim.mixnorm$crps.alt.conf)) })
test_that("next_k_e_values work as expected mixnorm - e.value.alt.conf", { expect_equal(length(result.next.k.clim.mixnorm$e.value.alt.conf), 11) })
test_that("next_k_e_values work as expected mixnorm - lambda.alt.conf", { expect_equal(length(result.next.k.clim.mixnorm$lambda.alt.conf), 11) })
test_that("next_k_e_values work as expected mixnorm - e.value.alt.conf.prod", { expect_equal(length(result.next.k.clim.mixnorm$e.value.alt.conf.prod), 1) })
test_that("next_k_e_values work as expected mixnorm - e.value.alt.conf.prod - type", { expect_type(result.next.k.clim.mixnorm$e.value.alt.conf.prod, "double") })
test_that("next_k_e_values work as expected mixnorm - crps.alt.more.cons", { expect_true(is.matrix(result.next.k.clim.mixnorm$crps.alt.more.cons)) })
test_that("next_k_e_values work as expected mixnorm - e.value.alt.more.cons", { expect_equal(length(result.next.k.clim.mixnorm$e.value.alt.more.cons), 11) })
test_that("next_k_e_values work as expected mixnorm - lambda.alt.more.cons", { expect_equal(length(result.next.k.clim.mixnorm$lambda.alt.more.cons), 11) })
test_that("next_k_e_values work as expected mixnorm - e.value.alt.more.cons.prod", { expect_equal(length(result.next.k.clim.mixnorm$e.value.alt.more.cons.prod), 1) })
test_that("next_k_e_values work as expected mixnorm - e.value.alt.more.cons.prod - type", { expect_type(result.next.k.clim.mixnorm$e.value.alt.more.cons.prod, "double") })