library(testthat)

####### e_value
result <- e_value(stats::rnorm(10), forecast_input(mu = stats::rnorm(10), sd = 1), forecast_input(mu = -stats::rnorm(10), sd = 1), method = c("alt-cons","GRAPA", "lambda", "alt-conf", "alt-more-cons"), p.value.method = "t")
test_that("test e_value does return evalue", { expect_type(result, "list") })
test_that("test e_value does return evalue - length y", { expect_equal(length(result$y), 10) })
test_that("test e_value does return evalue - crps.F length", { expect_equal(length(result$crps.F), 10) })
test_that("test e_value does return evalue - crps.F.para length", { expect_equal(length(result$crps.F.para), 7) })
test_that("test e_value does return evalue - crps.F.para - length mu", { expect_equal(length(result$crps.F.para$mu), 10) })
test_that("test e_value does return evalue - crps.F.para - length sd", { expect_equal(length(result$crps.F.para$sd), 1) })
test_that("test e_value does return evalue - crps.F.para types - fun", { expect_type(result$crps.F.para$fun, "closure") })
test_that("test e_value does return evalue - crps.F.para types - crps.fun.y.matrix", { expect_type(result$crps.F.para$crps.fun.y.matrix, "closure") })
test_that("test e_value does return evalue - crps.F.para types - sample.fun", { expect_type(result$crps.F.para$sample.fun, "closure") })
test_that("test e_value does return evalue - crps.F.para types - inf.fun", { expect_type(result$crps.F.para$inf.fun, "closure") })
test_that("test e_value does return evalue - crps.F.para - method", { expect_equal(result$crps.F.para$method, "norm") })
test_that("test e_value does return evalue - crps.G.para length", { expect_equal(length(result$crps.G.para), 7) })
test_that("test e_value does return evalue - crps.G length", { expect_equal(length(result$crps.G), 10) })
test_that("test e_value does return evalue - crps.G.para - length mu", { expect_equal(length(result$crps.G.para$mu), 10) })
test_that("test e_value does return evalue - crps.G.para - length sd", { expect_equal(length(result$crps.G.para$sd), 1) })
test_that("test e_value does return evalue - crps.G.para types - fun", { expect_type(result$crps.G.para$fun, "closure") })
test_that("test e_value does return evalue - crps.G.para types - crps.fun.y.matrix", { expect_type(result$crps.G.para$crps.fun.y.matrix, "closure") })
test_that("test e_value does return evalue - crps.G.para types - sample.fun", { expect_type(result$crps.G.para$sample.fun, "closure") })
test_that("test e_value does return evalue - crps.G.para types - inf.fun", { expect_type(result$crps.G.para$inf.fun, "closure") })
test_that("test e_value does return evalue - crps.G.para - method", { expect_equal(result$crps.G.para$method, "norm") })
test_that("test e_value does return evalue - inf.crps type", { expect_type(result$inf.crps, "double") })
test_that("test e_value does return evalue - method", { expect_equal(result$method, c("alt-cons","GRAPA", "lambda", "alt-conf", "alt-more-cons")) })
test_that("test e_value does return evalue - p.value.method", { expect_equal(result$p.value.method, "t") })
test_that("test e_value does return evalue - p.value", { expect_equal(length(result$p.value), 1) })
test_that("test e_value does return evalue - crps.alt.cons", { expect_true(is.matrix(result$crps.alt.cons)) })
test_that("test e_value does return evalue - e.value.alt.cons", { expect_equal(length(result$e.value.alt.cons), 10) })
test_that("test e_value does return evalue - lambda.alt.cons", { expect_equal(length(result$lambda.alt.cons), 10) })
test_that("test e_value does return evalue - e.value.alt.cons.prod", { expect_equal(length(result$e.value.alt.cons.prod), 1) })
test_that("test e_value does return evalue - e.value.alt.cons.prod - type", { expect_type(result$e.value.alt.cons.prod, "double") })
test_that("test e_value does return evalue - crps.alt.conf", { expect_true(is.matrix(result$crps.alt.conf)) })
test_that("test e_value does return evalue - e.value.alt.conf", { expect_equal(length(result$e.value.alt.conf), 10) })
test_that("test e_value does return evalue - lambda.alt.conf", { expect_equal(length(result$lambda.alt.conf), 10) })
test_that("test e_value does return evalue - e.value.alt.conf.prod", { expect_equal(length(result$e.value.alt.conf.prod), 1) })
test_that("test e_value does return evalue - e.value.alt.conf.prod - type", { expect_type(result$e.value.alt.conf.prod, "double") })
test_that("test e_value does return evalue - crps.alt.more.cons", { expect_true(is.matrix(result$crps.alt.more.cons)) })
test_that("test e_value does return evalue - e.value.alt.more.cons", { expect_equal(length(result$e.value.alt.more.cons), 10) })
test_that("test e_value does return evalue - lambda.alt.more.cons", { expect_equal(length(result$lambda.alt.more.cons), 10) })
test_that("test e_value does return evalue - e.value.alt.more.cons.prod", { expect_equal(length(result$e.value.alt.more.cons.prod), 1) })
test_that("test e_value does return evalue - e.value.alt.more.cons.prod - type", { expect_type(result$e.value.alt.more.cons.prod, "double") })

result.p.value.dm <- e_value(stats::rnorm(10), forecast_input(mu = stats::rnorm(10), sd = 1), forecast_input(mu = -stats::rnorm(10), sd = 1), method = c("alt-cons","GRAPA", "lambda", "alt-conf", "alt-more-cons"), p.value.method = "dm")
test_that("test p_value does return pvalue", { expect_type(result.p.value.dm, "list") })
test_that("test p_value does return pvalue - p.value length", { expect_equal(length(result.p.value.dm$p.value), 1) })
test_that("test p_value does return pvalue - p.value.method", { expect_equal(result.p.value.dm$p.value.method, "dm") })

# mixnorm
mu <- stats::rnorm(10)
tau <- sample(c(-1, 1), 10, replace = TRUE)
result.mixnorm <- e_value(stats::rnorm(10), forecast_input(mu = mu, sd = 1), forecast_input(mu = cbind(mu, mu + tau), sd = matrix(nrow = 10, ncol = 2, 1), w = matrix(nrow = 10, ncol = 2, 1 / 2)), method = c("alt-cons","GRAPA", "lambda", "alt-conf", "alt-more-cons"), p.value.method = "t")
test_that("test e_value does return evalue for mixnorm", { expect_type(result.mixnorm, "list") })
test_that("test e_value does return evalue for mixnorm - length y", { expect_equal(length(result.mixnorm$y), 10) })
test_that("test e_value does return evalue for mixnorm - crps.F length", { expect_equal(length(result.mixnorm$crps.F), 10) })
test_that("test e_value does return evalue for mixnorm - crps.F.para length", { expect_equal(length(result.mixnorm$crps.F.para), 7) })
test_that("test e_value does return evalue for mixnorm - crps.F.para - length mu", { expect_equal(length(result.mixnorm$crps.F.para$mu), 10) })
test_that("test e_value does return evalue for mixnorm - crps.F.para - length sd", { expect_equal(length(result.mixnorm$crps.F.para$sd), 1) })
test_that("test e_value does return evalue for mixnorm - crps.F.para types - fun", { expect_type(result.mixnorm$crps.F.para$fun, "closure") })
test_that("test e_value does return evalue for mixnorm - crps.F.para types - crps.fun.y.matrix", { expect_type(result.mixnorm$crps.F.para$crps.fun.y.matrix, "closure") })
test_that("test e_value does return evalue for mixnorm - crps.F.para types - sample.fun", { expect_type(result.mixnorm$crps.F.para$sample.fun, "closure") })
test_that("test e_value does return evalue for mixnorm - crps.F.para types - inf.fun", { expect_type(result.mixnorm$crps.F.para$inf.fun, "closure") })
test_that("test e_value does return evalue for mixnorm - crps.F.para - method", { expect_equal(result.mixnorm$crps.F.para$method, "norm") })
test_that("test e_value does return evalue for mixnorm - crps.G.para length", { expect_equal(length(result.mixnorm$crps.G.para), 8) })
test_that("test e_value does return evalue for mixnorm - crps.G length", { expect_equal(length(result.mixnorm$crps.G), 10) })
test_that("test e_value does return evalue for mixnorm - crps.G.para - dim mu", { expect_equal(dim(result.mixnorm$crps.G.para$mu), c(10, 2)) })
test_that("test e_value does return evalue for mixnorm - crps.G.para - dim sd", { expect_equal(dim(result.mixnorm$crps.G.para$sd), c(10,2)) })
test_that("test e_value does return evalue for mixnorm - crps.G.para - dim w", { expect_equal(dim(result.mixnorm$crps.G.para$w), c(10,2)) })
test_that("test e_value does return evalue for mixnorm - crps.G.para types - fun", { expect_type(result.mixnorm$crps.G.para$fun, "closure") })
test_that("test e_value does return evalue for mixnorm - crps.G.para types - crps.fun.y.matrix", { expect_type(result.mixnorm$crps.G.para$crps.fun.y.matrix, "closure") })
test_that("test e_value does return evalue for mixnorm - crps.G.para types - sample.fun", { expect_type(result.mixnorm$crps.G.para$sample.fun, "closure") })
test_that("test e_value does return evalue for mixnorm - crps.G.para types - inf.fun", { expect_type(result.mixnorm$crps.G.para$inf.fun, "closure") })
test_that("test e_value does return evalue for mixnorm - crps.G.para - method", { expect_equal(result.mixnorm$crps.G.para$method, "mixnorm") })
test_that("test e_value does return evalue for mixnorm - inf.crps type", { expect_type(result.mixnorm$inf.crps, "double") })
test_that("test e_value does return evalue for mixnorm - method", { expect_equal(result.mixnorm$method, c("alt-cons","GRAPA", "lambda", "alt-conf", "alt-more-cons")) })
test_that("test e_value does return evalue for mixnorm - p.value.method", { expect_equal(result.mixnorm$p.value.method, "t") })
test_that("test e_value does return evalue for mixnorm - p.value", { expect_equal(length(result.mixnorm$p.value), 1) })
test_that("test e_value does return evalue for mixnorm - crps.alt.cons", { expect_true(is.matrix(result.mixnorm$crps.alt.cons)) })
test_that("test e_value does return evalue for mixnorm - e.value.alt.cons", { expect_equal(length(result.mixnorm$e.value.alt.cons), 10) })
test_that("test e_value does return evalue for mixnorm - lambda.alt.cons", { expect_equal(length(result.mixnorm$lambda.alt.cons), 10) })
test_that("test e_value does return evalue for mixnorm - e.value.alt.cons.prod", { expect_equal(length(result.mixnorm$e.value.alt.cons.prod), 1) })
test_that("test e_value does return evalue for mixnorm - e.value.alt.cons.prod - type", { expect_type(result.mixnorm$e.value.alt.cons.prod, "double") })
test_that("test e_value does return evalue for mixnorm - crps.alt.conf", { expect_true(is.matrix(result$crps.alt.conf)) })
test_that("test e_value does return evalue for mixnorm - e.value.alt.conf", { expect_equal(length(result$e.value.alt.conf), 10) })
test_that("test e_value does return evalue for mixnorm - lambda.alt.conf", { expect_equal(length(result$lambda.alt.conf), 10) })
test_that("test e_value does return evalue for mixnorm - e.value.alt.conf.prod", { expect_equal(length(result$e.value.alt.conf.prod), 1) })
test_that("test e_value does return evalue for mixnorm - e.value.alt.conf.prod - type", { expect_type(result$e.value.alt.conf.prod, "double") })
test_that("test e_value does return evalue for mixnorm - crps.alt.more.cons", { expect_true(is.matrix(result$crps.alt.more.cons)) })
test_that("test e_value does return evalue for mixnorm - e.value.alt.more.cons", { expect_equal(length(result$e.value.alt.more.cons), 10) })
test_that("test e_value does return evalue for mixnorm - lambda.alt.more.cons", { expect_equal(length(result$lambda.alt.more.cons), 10) })
test_that("test e_value does return evalue for mixnorm - e.value.alt.more.cons.prod", { expect_equal(length(result$e.value.alt.more.cons.prod), 1) })
test_that("test e_value does return evalue for mixnorm - e.value.alt.more.cons.prod - type", { expect_type(result$e.value.alt.more.cons.prod, "double") })

# mixnorm - climatologocial
mu <- stats::rnorm(10)
tau <- sample(c(-1, 1), 10, replace = TRUE)
result.clim.mixnorm <- e_value(rnorm(10), forecast_input(mu = 0, sd = 1), forecast_input(mu = cbind(mu, mu + tau), sd = matrix(nrow = 10, ncol = 2, 1), w = matrix(nrow = 10, ncol = 2, 1 / 2)), method = c("alt-cons","GRAPA", "lambda", "alt-conf", "alt-more-cons"), p.value.method = "t")
test_that("test e_value does return evalue for mixnorm and climatological", { expect_type(result.clim.mixnorm, "list") })

####### sequential run of e_value
mu <- stats::rnorm(10)
y <- stats::rnorm(10, mu)
result.next.k.first <- e_value(y = y, crps.F.para = list("mu" = mu, "sd" = 1), crps.G.para = list("mu" = 0, "sd" = 2), method = c("alt-cons","GRAPA", "lambda", "alt-conf", "alt-more-cons"), p.value.method = "t")
new.mu <- stats::rnorm(1)
result.next.k <- e_value(old.run.e.value = result.next.k.first, new.y = stats::rnorm(1, new.mu), new.crps.F.para = list("mu" = new.mu, "sd" = NA), new.crps.G.para = list("mu" = NA, "sd" = NA))
test_that("e_value sequential work as expected - dim crps.alt.cons", { expect_equal(dim(result.next.k$crps.alt.cons), c(11, 50)) })
test_that("e_value sequential work as expected - length y", { expect_equal(length(result.next.k$y), 11) })
test_that("e_value sequential work as expected - crps.F length", { expect_equal(length(result.next.k$crps.F), 11) })
test_that("e_value sequential work as expected - crps.F.para length", { expect_equal(length(result.next.k$crps.F.para), 7) })
test_that("e_value sequential work as expected - crps.F.para - length mu", { expect_equal(length(result.next.k$crps.F.para$mu), 11) })
test_that("e_value sequential work as expected - crps.F.para - mu", { expect_equal(result.next.k$crps.F.para$mu, c(mu, new.mu)) })
test_that("e_value sequential work as expected - crps.F.para - length sd", { expect_equal(length(result.next.k$crps.F.para$sd), 1) })
test_that("e_value sequential work as expected - crps.F.para types - fun", { expect_type(result.next.k$crps.F.para$fun, "closure") })
test_that("e_value sequential work as expected - crps.F.para types - crps.fun.y.matrix", { expect_type(result.next.k$crps.F.para$crps.fun.y.matrix, "closure") })
test_that("e_value sequential work as expected - crps.F.para types - sample.fun", { expect_type(result.next.k$crps.F.para$sample.fun, "closure") })
test_that("e_value sequential work as expected - crps.F.para types - inf.fun", { expect_type(result.next.k$crps.F.para$inf.fun, "closure") })
test_that("e_value sequential work as expected - crps.F.para - method", { expect_equal(result.next.k$crps.F.para$method, "norm") })
test_that("e_value sequential work as expected - crps.G.para length", { expect_equal(length(result.next.k$crps.G.para), 7) })
test_that("e_value sequential work as expected - crps.G length", { expect_equal(length(result.next.k$crps.G), 11) })
test_that("e_value sequential work as expected - crps.G.para - length mu", { expect_equal(length(result.next.k$crps.G.para$mu), 1) })
test_that("e_value sequential work as expected - crps.G.para - length sd", { expect_equal(length(result.next.k$crps.G.para$sd), 1) })
test_that("e_value sequential work as expected - crps.G.para types - fun", { expect_type(result.next.k$crps.G.para$fun, "closure") })
test_that("e_value sequential work as expected - crps.G.para types - crps.fun.y.matrix", { expect_type(result.next.k$crps.G.para$crps.fun.y.matrix, "closure") })
test_that("e_value sequential work as expected - crps.G.para types - sample.fun", { expect_type(result.next.k$crps.G.para$sample.fun, "closure") })
test_that("e_value sequential work as expected - crps.G.para types - inf.fun", { expect_type(result.next.k$crps.G.para$inf.fun, "closure") })
test_that("e_value sequential work as expected - crps.G.para - method", { expect_equal(result.next.k$crps.G.para$method, "norm") })
test_that("e_value sequential work as expected - inf.crps type", { expect_type(result.next.k$inf.crps, "double") })
test_that("e_value sequential work as expected - method", { expect_equal(result.next.k$method, c("alt-cons","GRAPA", "lambda", "alt-conf", "alt-more-cons")) })
test_that("e_value sequential work as expected - p.value.method", { expect_equal(result.next.k$p.value.method, "t") })
test_that("e_value sequential work as expected - p.value", { expect_equal(length(result.next.k$p.value), 1) })
test_that("e_value sequential work as expected - crps.alt.cons", { expect_equal(dim(result.next.k$crps.alt.cons), c(11, 50)) })
test_that("e_value sequential work as expected - e.value.alt.cons", { expect_equal(length(result.next.k$e.value.alt.cons), 11) })
test_that("e_value sequential work as expected - lambda.alt.cons", { expect_equal(length(result.next.k$lambda.alt.cons), 11) })
test_that("e_value sequential work as expected - e.value.alt.cons.prod", { expect_equal(length(result.next.k$e.value.alt.cons.prod), 1) })
test_that("e_value sequential work as expected - e.value.alt.cons.prod - type", { expect_type(result.next.k$e.value.alt.cons.prod, "double") })
test_that("e_value sequential work as expected - crps.alt.conf", { expect_true(is.matrix(result.next.k$crps.alt.conf)) })
test_that("e_value sequential work as expected - e.value.alt.conf", { expect_equal(length(result.next.k$e.value.alt.conf), 11) })
test_that("e_value sequential work as expected - lambda.alt.conf", { expect_equal(length(result.next.k$lambda.alt.conf), 11) })
test_that("e_value sequential work as expected - e.value.alt.conf.prod", { expect_equal(length(result.next.k$e.value.alt.conf.prod), 1) })
test_that("e_value sequential work as expected - e.value.alt.conf.prod - type", { expect_type(result.next.k$e.value.alt.conf.prod, "double") })
test_that("e_value sequential work as expected - crps.alt.more.cons", { expect_true(is.matrix(result.next.k$crps.alt.more.cons)) })
test_that("e_value sequential work as expected - e.value.alt.more.cons", { expect_equal(length(result.next.k$e.value.alt.more.cons), 11) })
test_that("e_value sequential work as expected - lambda.alt.more.cons", { expect_equal(length(result.next.k$lambda.alt.more.cons), 11) })
test_that("e_value sequential work as expected - e.value.alt.more.cons.prod", { expect_equal(length(result.next.k$e.value.alt.more.cons.prod), 1) })
test_that("e_value sequential work as expected - e.value.alt.more.cons.prod - type", { expect_type(result.next.k$e.value.alt.more.cons.prod, "double") })

mu <- stats::rnorm(10)
tau <- sample(c(-1, 1), 10, replace = TRUE)
result.next.k.clim.mixnorm.first <- e_value(rnorm(10), forecast_input(mu = 0, sd = 1), forecast_input(mu = cbind(mu, mu + tau), sd = matrix(nrow = 10, ncol = 2, 1), w = matrix(nrow = 10, ncol = 2, 1 / 2)), method = c("alt-cons","GRAPA", "lambda", "alt-conf", "alt-more-cons"), p.value.method = "t")
new.mu <- stats::rnorm(1)
new.tau <- sample(c(-1, 1), 1)
result.next.k.clim.mixnorm <- e_value(old.run.e.value = result.next.k.clim.mixnorm.first, new.y = stats::rnorm(1, new.mu), new.crps.F.para = list("mu" = NA, "sd" = NA), new.crps.G.para = list("mu" = c(new.mu, new.mu + new.tau), "sd" = c(1,1), "w" = c(1/2, 1/2)))
test_that("e_value sequential work as expected mixnorm - dim crps.alt.cons", { expect_equal(dim(result.next.k.clim.mixnorm$crps.alt.cons), c(11, 50)) })
test_that("e_value sequential work as expected mixnorm - length y", { expect_equal(length(result.next.k.clim.mixnorm$y), 11) })
test_that("e_value sequential work as expected mixnorm - crps.F length", { expect_equal(length(result.next.k.clim.mixnorm$crps.F), 11) })
test_that("e_value sequential work as expected mixnorm - crps.F.para length", { expect_equal(length(result.next.k.clim.mixnorm$crps.F.para), 7) })
test_that("e_value sequential work as expected mixnorm - crps.F.para - length mu", { expect_equal(length(result.next.k.clim.mixnorm$crps.F.para$mu), 1) })
test_that("e_value sequential work as expected mixnorm - crps.F.para - length sd", { expect_equal(length(result.next.k.clim.mixnorm$crps.F.para$sd), 1) })
test_that("e_value sequential work as expected mixnorm - crps.F.para types - fun", { expect_type(result.next.k.clim.mixnorm$crps.F.para$fun, "closure") })
test_that("e_value sequential work as expected mixnorm - crps.F.para types - crps.fun.y.matrix", { expect_type(result.next.k.clim.mixnorm$crps.F.para$crps.fun.y.matrix, "closure") })
test_that("e_value sequential work as expected mixnorm - crps.F.para types - sample.fun", { expect_type(result.next.k.clim.mixnorm$crps.F.para$sample.fun, "closure") })
test_that("e_value sequential work as expected mixnorm - crps.F.para types - inf.fun", { expect_type(result.next.k.clim.mixnorm$crps.F.para$inf.fun, "closure") })
test_that("e_value sequential work as expected mixnorm - crps.F.para - method", { expect_equal(result.next.k.clim.mixnorm$crps.F.para$method, "norm") })
test_that("e_value sequential work as expected mixnorm - crps.G.para length", { expect_equal(length(result.next.k.clim.mixnorm$crps.G.para), 8) })
test_that("e_value sequential work as expected mixnorm - crps.G length", { expect_equal(length(result.next.k.clim.mixnorm$crps.G), 11) })
test_that("e_value sequential work as expected mixnorm - crps.G.para - mu matrix", { expect_true(is.matrix(result.next.k.clim.mixnorm$crps.G.para$mu)) })
test_that("e_value sequential work as expected mixnorm - crps.G.para - mu dim", { expect_equal(dim(result.next.k.clim.mixnorm$crps.G.para$mu), c(11, 2)) })
test_that("e_value sequential work as expected mixnorm - crps.G.para - sd matrix", { expect_true(is.matrix(result.next.k.clim.mixnorm$crps.G.para$sd)) })
test_that("e_value sequential work as expected mixnorm - crps.G.para - sd dim", { expect_equal(dim(result.next.k.clim.mixnorm$crps.G.para$sd), c(11, 2)) })
test_that("e_value sequential work as expected mixnorm - crps.G.para types - fun", { expect_type(result.next.k.clim.mixnorm$crps.G.para$fun, "closure") })
test_that("e_value sequential work as expected mixnorm - crps.G.para types - crps.fun.y.matrix", { expect_type(result.next.k.clim.mixnorm$crps.G.para$crps.fun.y.matrix, "closure") })
test_that("e_value sequential work as expected mixnorm - crps.G.para types - sample.fun", { expect_type(result.next.k.clim.mixnorm$crps.G.para$sample.fun, "closure") })
test_that("e_value sequential work as expected mixnorm - crps.G.para types - inf.fun", { expect_type(result.next.k.clim.mixnorm$crps.G.para$inf.fun, "closure") })
test_that("e_value sequential work as expected mixnorm - crps.G.para - method", { expect_equal(result.next.k.clim.mixnorm$crps.G.para$method, "mixnorm") })
test_that("e_value sequential work as expected mixnorm - inf.crps type", { expect_type(result.next.k.clim.mixnorm$inf.crps, "double") })
test_that("e_value sequential work as expected mixnorm - method", { expect_equal(result.next.k.clim.mixnorm$method, c("alt-cons","GRAPA", "lambda", "alt-conf", "alt-more-cons")) })
test_that("e_value sequential work as expected mixnorm - p.value.method", { expect_equal(result.next.k.clim.mixnorm$p.value.method, "t") })
test_that("e_value sequential work as expected mixnorm - p.value", { expect_equal(length(result.next.k.clim.mixnorm$p.value), 1) })
test_that("e_value sequential work as expected mixnorm - crps.alt.cons", { expect_equal(dim(result.next.k.clim.mixnorm$crps.alt.cons), c(11, 50)) })
test_that("e_value sequential work as expected mixnorm - e.value.alt.cons", { expect_equal(length(result.next.k.clim.mixnorm$e.value.alt.cons), 11) })
test_that("e_value sequential work as expected mixnorm - lambda.alt.cons", { expect_equal(length(result.next.k.clim.mixnorm$lambda.alt.cons), 11) })
test_that("e_value sequential work as expected mixnorm - e.value.alt.cons.prod", { expect_equal(length(result.next.k.clim.mixnorm$e.value.alt.cons.prod), 1) })
test_that("e_value sequential work as expected mixnorm - e.value.alt.cons.prod - type", { expect_type(result.next.k.clim.mixnorm$e.value.alt.cons.prod, "double") })
test_that("e_value sequential work as expected mixnorm - crps.alt.conf", { expect_true(is.matrix(result.next.k.clim.mixnorm$crps.alt.conf)) })
test_that("e_value sequential work as expected mixnorm - e.value.alt.conf", { expect_equal(length(result.next.k.clim.mixnorm$e.value.alt.conf), 11) })
test_that("e_value sequential work as expected mixnorm - lambda.alt.conf", { expect_equal(length(result.next.k.clim.mixnorm$lambda.alt.conf), 11) })
test_that("e_value sequential work as expected mixnorm - e.value.alt.conf.prod", { expect_equal(length(result.next.k.clim.mixnorm$e.value.alt.conf.prod), 1) })
test_that("e_value sequential work as expected mixnorm - e.value.alt.conf.prod - type", { expect_type(result.next.k.clim.mixnorm$e.value.alt.conf.prod, "double") })
test_that("e_value sequential work as expected mixnorm - crps.alt.more.cons", { expect_true(is.matrix(result.next.k.clim.mixnorm$crps.alt.more.cons)) })
test_that("e_value sequential work as expected mixnorm - e.value.alt.more.cons", { expect_equal(length(result.next.k.clim.mixnorm$e.value.alt.more.cons), 11) })
test_that("e_value sequential work as expected mixnorm - lambda.alt.more.cons", { expect_equal(length(result.next.k.clim.mixnorm$lambda.alt.more.cons), 11) })
test_that("e_value sequential work as expected mixnorm - e.value.alt.more.cons.prod", { expect_equal(length(result.next.k.clim.mixnorm$e.value.alt.more.cons.prod), 1) })
test_that("e_value sequential work as expected mixnorm - e.value.alt.more.cons.prod - type", { expect_type(result.next.k.clim.mixnorm$e.value.alt.more.cons.prod, "double") })

# raw forecasts
crps.F.para <- list("points.cdf" = list(tibble("points" = base::sort(stats::runif(10, 0, 15)), "cdf" = c(base::sort(stats::runif(9, 0,1)), 1)), tibble::tibble("points" = base::sort(stats::runif(10, 0, 15)), "cdf" = c(base::sort(stats::runif(9, 0,1)), 1))))
crps.G.para <- list("points.cdf" = list(tibble("points" = base::sort(stats::runif(15, 0, 20)), "cdf" = c(base::sort(stats::runif(14, 0, 1)), 1)), tibble::tibble("points" = base::sort(stats::runif(15, 0, 20)), "cdf" = c(base::sort(stats::runif(14, 0, 1)), 1))))
e.value.rf.first <- e_value(y = stats::runif(2, 0, 10), crps.F.para = crps.F.para, crps.G.para = crps.G.para, method = c("alt-cons","GRAPA", "lambda", "alt-conf", "alt-more-cons"), p.value.method = "t")
result.next.k.rf <- e_value(old.run.e.value = e.value.rf.first, new.y = stats::runif(1, 0, 10), new.crps.F.para = list(tibble("points" = base::sort(stats::runif(10, 0, 15)), "cdf" = c(base::sort(stats::runif(9, 0,1)), 1))), new.crps.G.para = list(tibble("points" = base::sort(stats::runif(15, 0, 20)), "cdf" = c(base::sort(stats::runif(14, 0, 1)), 1))))
test_that("e_value sequential work as expected raw forecast - dim crps.alt.cons", { expect_equal(dim(result.next.k.rf$crps.alt.cons), c(3, 50)) })
test_that("e_value sequential work as expected raw forecast - length y", { expect_equal(length(result.next.k.rf$y), 3) })
test_that("e_value sequential work as expected raw forecast - crps.F length", { expect_equal(length(result.next.k.rf$crps.F), 3) })
test_that("e_value sequential work as expected raw forecast - crps.F.para length", { expect_equal(length(result.next.k.rf$crps.F.para), 6) })
test_that("e_value sequential work as expected raw forecast - crps.F.para - length points.cdf", { expect_equal(length(result.next.k.rf$crps.F.para$points.cdf), 3) })
test_that("e_value sequential work as expected raw forecast - crps.F.para types - fun", { expect_type(result.next.k.rf$crps.F.para$fun, "closure") })
test_that("e_value sequential work as expected raw forecast - crps.F.para types - crps.fun.y.matrix", { expect_type(result.next.k.rf$crps.F.para$crps.fun.y.matrix, "closure") })
test_that("e_value sequential work as expected raw forecast - crps.F.para types - sample.fun", { expect_type(result.next.k.rf$crps.F.para$sample.fun, "closure") })
test_that("e_value sequential work as expected raw forecast - crps.F.para types - inf.fun", { expect_type(result.next.k.rf$crps.F.para$inf.fun, "closure") })
test_that("e_value sequential work as expected raw forecast - crps.F.para - method", { expect_equal(result.next.k.rf$crps.F.para$method, "raw") })
test_that("e_value sequential work as expected raw forecast - crps.G.para length", { expect_equal(length(result.next.k.rf$crps.G.para), 6) })
test_that("e_value sequential work as expected raw forecast - crps.G length", { expect_equal(length(result.next.k.rf$crps.G), 3) })
test_that("e_value sequential work as expected raw forecast - crps.G.para - length points.cdf", { expect_equal(length(result.next.k.rf$crps.G.para$points.cdf), 3) })
test_that("e_value sequential work as expected raw forecast - crps.G.para types - fun", { expect_type(result.next.k.rf$crps.G.para$fun, "closure") })
test_that("e_value sequential work as expected raw forecast - crps.G.para types - crps.fun.y.matrix", { expect_type(result.next.k.rf$crps.G.para$crps.fun.y.matrix, "closure") })
test_that("e_value sequential work as expected raw forecast - crps.G.para types - sample.fun", { expect_type(result.next.k.rf$crps.G.para$sample.fun, "closure") })
test_that("e_value sequential work as expected raw forecast - crps.G.para types - inf.fun", { expect_type(result.next.k.rf$crps.G.para$inf.fun, "closure") })
test_that("e_value sequential work as expected raw forecast - crps.G.para - method", { expect_equal(result.next.k.rf$crps.G.para$method, "raw") })
test_that("e_value sequential work as expected raw forecast - inf.crps type", { expect_type(result.next.k.rf$inf.crps, "double") })
test_that("e_value sequential work as expected raw forecast - method", { expect_equal(result.next.k.rf$method, c("alt-cons","GRAPA", "lambda", "alt-conf", "alt-more-cons")) })
test_that("e_value sequential work as expected raw forecast - p.value.method", { expect_equal(result.next.k.rf$p.value.method, "t") })
test_that("e_value sequential work as expected raw forecast - p.value", { expect_equal(length(result.next.k.rf$p.value), 1) })
test_that("e_value sequential work as expected raw forecast - crps.alt.cons", { expect_equal(dim(result.next.k.rf$crps.alt.cons), c(3, 50)) })
test_that("e_value sequential work as expected raw forecast - e.value.alt.cons", { expect_equal(length(result.next.k.rf$e.value.alt.cons), 3) })
test_that("e_value sequential work as expected raw forecast - lambda.alt.cons", { expect_equal(length(result.next.k.rf$lambda.alt.cons), 3) })
test_that("e_value sequential work as expected raw forecast - e.value.alt.cons.prod", { expect_equal(length(result.next.k.rf$e.value.alt.cons.prod), 1) })
test_that("e_value sequential work as expected raw forecast - e.value.alt.cons.prod - type", { expect_type(result.next.k.rf$e.value.alt.cons.prod, "double") })
test_that("e_value sequential work as expected raw forecast - crps.alt.conf", { expect_true(is.matrix(result.next.k.rf$crps.alt.conf)) })
test_that("e_value sequential work as expected raw forecast - e.value.alt.conf", { expect_equal(length(result.next.k.rf$e.value.alt.conf), 3) })
test_that("e_value sequential work as expected raw forecast - lambda.alt.conf", { expect_equal(length(result.next.k.rf$lambda.alt.conf), 3) })
test_that("e_value sequential work as expected raw forecast - e.value.alt.conf.prod", { expect_equal(length(result.next.k.rf$e.value.alt.conf.prod), 1) })
test_that("e_value sequential work as expected raw forecast - e.value.alt.conf.prod - type", { expect_type(result.next.k.rf$e.value.alt.conf.prod, "double") })
test_that("e_value sequential work as expected raw forecast - crps.alt.more.cons", { expect_true(is.matrix(result.next.k.rf$crps.alt.more.cons)) })
test_that("e_value sequential work as expected raw forecast - e.value.alt.more.cons", { expect_equal(length(result.next.k.rf$e.value.alt.more.cons), 3) })
test_that("e_value sequential work as expected raw forecast - lambda.alt.more.cons", { expect_equal(length(result.next.k.rf$lambda.alt.more.cons), 3) })
test_that("e_value sequential work as expected raw forecast - e.value.alt.more.cons.prod", { expect_equal(length(result.next.k.rf$e.value.alt.more.cons.prod), 1) })
test_that("e_value sequential work as expected raw forecast - e.value.alt.more.cons.prod - type", { expect_type(result.next.k.rf$e.value.alt.more.cons.prod, "double") })


### different distirbution family - Student's t - 2 fun
n.obs <- 10
crps.F.para <- list("method" = 't', "fun" = \(y) {scoringRules::crps_t(y = y, df = 8)}, "sample.fun" = \(n, n.obs) {matrix(stats::rt(n * n.obs, df = 8), nrow = n.obs)})
e.value.student.t <- e_value(y = stats::runif(n.obs, 0, 10), crps.F.para = crps.F.para, crps.G.para = forecast_input(mu = stats::rnorm(n.obs), sd = 1), method = c("alt-cons","GRAPA", "lambda", "alt-conf", "alt-more-cons"), p.value.method = "t")
e.value.student.t.next.k <- e_value(old.run.e.value = e.value.student.t, new.y = stats::runif(1, 0, 10), new.crps.F.para = list(), new.crps.G.para = list("mu" = stats::rnorm(1), "sd" = NA))
test_that("e_value sequential work as expected for random distribution - dim crps.alt.cons", { expect_equal(dim(e.value.student.t.next.k$crps.alt.cons), c(11, 50)) })
test_that("e_value sequential work as expected for random distribution - length y", { expect_equal(length(e.value.student.t.next.k$y), 11) })
test_that("e_value sequential work as expected for random distribution - crps.F length", { expect_equal(length(e.value.student.t.next.k$crps.F), 11) })
test_that("e_value sequential work as expected for random distribution - crps.F.para length", { expect_equal(length(e.value.student.t.next.k$crps.F.para), 5) })
test_that("e_value sequential work as expected for random distribution - crps.F.para types - fun", { expect_type(e.value.student.t.next.k$crps.F.para$fun, "closure") })
test_that("e_value sequential work as expected for random distribution - crps.F.para types - crps.fun.y.matrix", { expect_type(e.value.student.t.next.k$crps.F.para$crps.fun.y.matrix, "closure") })
test_that("e_value sequential work as expected for random distribution - crps.F.para types - sample.fun", { expect_type(e.value.student.t.next.k$crps.F.para$sample.fun, "closure") })
test_that("e_value sequential work as expected for random distribution - crps.F.para types - inf.fun", { expect_type(e.value.student.t.next.k$crps.F.para$inf.fun, "closure") })
test_that("e_value sequential work as expected for random distribution - crps.F.para - method", { expect_equal(e.value.student.t.next.k$crps.F.para$method, "t") })
test_that("e_value sequential work as expected for random distribution - crps.G.para length", { expect_equal(length(e.value.student.t.next.k$crps.G.para), 7) })
test_that("e_value sequential work as expected for random distribution - crps.G length", { expect_equal(length(e.value.student.t.next.k$crps.G), 11) })
test_that("e_value sequential work as expected for random distribution - crps.G.para - length mu", { expect_equal(length(e.value.student.t.next.k$crps.G.para$mu), 11) })
test_that("e_value sequential work as expected for random distribution - crps.G.para - length sd", { expect_equal(length(e.value.student.t.next.k$crps.G.para$sd), 1) })
test_that("e_value sequential work as expected for random distribution - crps.G.para types - fun", { expect_type(e.value.student.t.next.k$crps.G.para$fun, "closure") })
test_that("e_value sequential work as expected for random distribution - crps.G.para types - crps.fun.y.matrix", { expect_type(e.value.student.t.next.k$crps.G.para$crps.fun.y.matrix, "closure") })
test_that("e_value sequential work as expected for random distribution - crps.G.para types - sample.fun", { expect_type(e.value.student.t.next.k$crps.G.para$sample.fun, "closure") })
test_that("e_value sequential work as expected for random distribution - crps.G.para types - inf.fun", { expect_type(e.value.student.t.next.k$crps.G.para$inf.fun, "closure") })
test_that("e_value sequential work as expected for random distribution - crps.G.para - method", { expect_equal(e.value.student.t.next.k$crps.G.para$method, "norm") })
test_that("e_value sequential work as expected for random distribution - inf.crps type", { expect_type(e.value.student.t.next.k$inf.crps, "double") })
test_that("e_value sequential work as expected for random distribution - method", { expect_equal(e.value.student.t.next.k$method, c("alt-cons","GRAPA", "lambda", "alt-conf", "alt-more-cons")) })
test_that("e_value sequential work as expected for random distribution - p.value.method", { expect_equal(e.value.student.t.next.k$p.value.method, "t") })
test_that("e_value sequential work as expected for random distribution - p.value", { expect_equal(length(e.value.student.t.next.k$p.value), 1) })
test_that("e_value sequential work as expected for random distribution - crps.alt.cons", { expect_equal(dim(e.value.student.t.next.k$crps.alt.cons), c(11, 50)) })
test_that("e_value sequential work as expected for random distribution - e.value.alt.cons", { expect_equal(length(e.value.student.t.next.k$e.value.alt.cons), 11) })
test_that("e_value sequential work as expected for random distribution - lambda.alt.cons", { expect_equal(length(e.value.student.t.next.k$lambda.alt.cons), 11) })
test_that("e_value sequential work as expected for random distribution - e.value.alt.cons.prod", { expect_equal(length(e.value.student.t.next.k$e.value.alt.cons.prod), 1) })
test_that("e_value sequential work as expected for random distribution - e.value.alt.cons.prod - type", { expect_type(e.value.student.t.next.k$e.value.alt.cons.prod, "double") })
test_that("e_value sequential work as expected for random distribution - crps.alt.conf", { expect_true(is.matrix(e.value.student.t.next.k$crps.alt.conf)) })
test_that("e_value sequential work as expected for random distribution - e.value.alt.conf", { expect_equal(length(e.value.student.t.next.k$e.value.alt.conf), 11) })
test_that("e_value sequential work as expected for random distribution - lambda.alt.conf", { expect_equal(length(e.value.student.t.next.k$lambda.alt.conf), 11) })
test_that("e_value sequential work as expected for random distribution - e.value.alt.conf.prod", { expect_equal(length(e.value.student.t.next.k$e.value.alt.conf.prod), 1) })
test_that("e_value sequential work as expected for random distribution - e.value.alt.conf.prod - type", { expect_type(e.value.student.t.next.k$e.value.alt.conf.prod, "double") })
test_that("e_value sequential work as expected for random distribution - crps.alt.more.cons", { expect_true(is.matrix(e.value.student.t.next.k$crps.alt.more.cons)) })
test_that("e_value sequential work as expected for random distribution - e.value.alt.more.cons", { expect_equal(length(e.value.student.t.next.k$e.value.alt.more.cons), 11) })
test_that("e_value sequential work as expected for random distribution - lambda.alt.more.cons", { expect_equal(length(e.value.student.t.next.k$lambda.alt.more.cons), 11) })
test_that("e_value sequential work as expected for random distribution - e.value.alt.more.cons.prod", { expect_equal(length(e.value.student.t.next.k$e.value.alt.more.cons.prod), 1) })
test_that("e_value sequential work as expected for random distribution - e.value.alt.more.cons.prod - type", { expect_type(e.value.student.t.next.k$e.value.alt.more.cons.prod, "double") })

## 4 functions defined
n.obs <- 10
crps.F.para <- list("method" = 't', "fun" = \(y) {scoringRules::crps_t(y = y, df = 8)}, "crps.fun.y.matrix" = \(y) {scoringRules::crps_t(y = y, df = 8)}, "sample.fun" = \(n, n.obs) {matrix(stats::rt(n * n.obs, df = 8), nrow = n.obs)}, "inf.fun" = \(x,j) {scoringRules::crps_t(y = x, df = 8)})
e.value.student.t <- e_value(y = stats::runif(n.obs, 0, 10), crps.F.para = crps.F.para, crps.G.para = forecast_input(mu = stats::rnorm(n.obs), sd = 1), method = c("alt-cons","GRAPA", "lambda", "alt-conf", "alt-more-cons"), p.value.method = "t")
e.value.student.t.next.k <- e_value(old.run.e.value = e.value.student.t, new.y = stats::runif(1, 0, 10), new.crps.F.para = list(), new.crps.G.para = list("mu" = stats::rnorm(1), "sd" = NA))
test_that("e_value sequential work as expected for random distribution - dim crps.alt.cons", { expect_equal(dim(e.value.student.t.next.k$crps.alt.cons), c(11, 50)) })
test_that("e_value sequential work as expected for random distribution - length y", { expect_equal(length(e.value.student.t.next.k$y), 11) })
test_that("e_value sequential work as expected for random distribution - crps.F length", { expect_equal(length(e.value.student.t.next.k$crps.F), 11) })
test_that("e_value sequential work as expected for random distribution - crps.F.para length", { expect_equal(length(e.value.student.t.next.k$crps.F.para), 5) })
test_that("e_value sequential work as expected for random distribution - crps.F.para types - fun", { expect_type(e.value.student.t.next.k$crps.F.para$fun, "closure") })
test_that("e_value sequential work as expected for random distribution - crps.F.para types - crps.fun.y.matrix", { expect_type(e.value.student.t.next.k$crps.F.para$crps.fun.y.matrix, "closure") })
test_that("e_value sequential work as expected for random distribution - crps.F.para types - sample.fun", { expect_type(e.value.student.t.next.k$crps.F.para$sample.fun, "closure") })
test_that("e_value sequential work as expected for random distribution - crps.F.para types - inf.fun", { expect_type(e.value.student.t.next.k$crps.F.para$inf.fun, "closure") })
test_that("e_value sequential work as expected for random distribution - crps.F.para - method", { expect_equal(e.value.student.t.next.k$crps.F.para$method, "t") })
test_that("e_value sequential work as expected for random distribution - crps.G.para length", { expect_equal(length(e.value.student.t.next.k$crps.G.para), 7) })
test_that("e_value sequential work as expected for random distribution - crps.G length", { expect_equal(length(e.value.student.t.next.k$crps.G), 11) })
test_that("e_value sequential work as expected for random distribution - crps.G.para - length mu", { expect_equal(length(e.value.student.t.next.k$crps.G.para$mu), 11) })
test_that("e_value sequential work as expected for random distribution - crps.G.para - length sd", { expect_equal(length(e.value.student.t.next.k$crps.G.para$sd), 1) })
test_that("e_value sequential work as expected for random distribution - crps.G.para types - fun", { expect_type(e.value.student.t.next.k$crps.G.para$fun, "closure") })
test_that("e_value sequential work as expected for random distribution - crps.G.para types - crps.fun.y.matrix", { expect_type(e.value.student.t.next.k$crps.G.para$crps.fun.y.matrix, "closure") })
test_that("e_value sequential work as expected for random distribution - crps.G.para types - sample.fun", { expect_type(e.value.student.t.next.k$crps.G.para$sample.fun, "closure") })
test_that("e_value sequential work as expected for random distribution - crps.G.para types - inf.fun", { expect_type(e.value.student.t.next.k$crps.G.para$inf.fun, "closure") })
test_that("e_value sequential work as expected for random distribution - crps.G.para - method", { expect_equal(e.value.student.t.next.k$crps.G.para$method, "norm") })
test_that("e_value sequential work as expected for random distribution - inf.crps type", { expect_type(e.value.student.t.next.k$inf.crps, "double") })
test_that("e_value sequential work as expected for random distribution - method", { expect_equal(e.value.student.t.next.k$method, c("alt-cons","GRAPA", "lambda", "alt-conf", "alt-more-cons")) })
test_that("e_value sequential work as expected for random distribution - p.value.method", { expect_equal(e.value.student.t.next.k$p.value.method, "t") })
test_that("e_value sequential work as expected for random distribution - p.value", { expect_equal(length(e.value.student.t.next.k$p.value), 1) })
test_that("e_value sequential work as expected for random distribution - crps.alt.cons", { expect_equal(dim(e.value.student.t.next.k$crps.alt.cons), c(11, 50)) })
test_that("e_value sequential work as expected for random distribution - e.value.alt.cons", { expect_equal(length(e.value.student.t.next.k$e.value.alt.cons), 11) })
test_that("e_value sequential work as expected for random distribution - lambda.alt.cons", { expect_equal(length(e.value.student.t.next.k$lambda.alt.cons), 11) })
test_that("e_value sequential work as expected for random distribution - e.value.alt.cons.prod", { expect_equal(length(e.value.student.t.next.k$e.value.alt.cons.prod), 1) })
test_that("e_value sequential work as expected for random distribution - e.value.alt.cons.prod - type", { expect_type(e.value.student.t.next.k$e.value.alt.cons.prod, "double") })
test_that("e_value sequential work as expected for random distribution - crps.alt.conf", { expect_true(is.matrix(e.value.student.t.next.k$crps.alt.conf)) })
test_that("e_value sequential work as expected for random distribution - e.value.alt.conf", { expect_equal(length(e.value.student.t.next.k$e.value.alt.conf), 11) })
test_that("e_value sequential work as expected for random distribution - lambda.alt.conf", { expect_equal(length(e.value.student.t.next.k$lambda.alt.conf), 11) })
test_that("e_value sequential work as expected for random distribution - e.value.alt.conf.prod", { expect_equal(length(e.value.student.t.next.k$e.value.alt.conf.prod), 1) })
test_that("e_value sequential work as expected for random distribution - e.value.alt.conf.prod - type", { expect_type(e.value.student.t.next.k$e.value.alt.conf.prod, "double") })
test_that("e_value sequential work as expected for random distribution - crps.alt.more.cons", { expect_true(is.matrix(e.value.student.t.next.k$crps.alt.more.cons)) })
test_that("e_value sequential work as expected for random distribution - e.value.alt.more.cons", { expect_equal(length(e.value.student.t.next.k$e.value.alt.more.cons), 11) })
test_that("e_value sequential work as expected for random distribution - lambda.alt.more.cons", { expect_equal(length(e.value.student.t.next.k$lambda.alt.more.cons), 11) })
test_that("e_value sequential work as expected for random distribution - e.value.alt.more.cons.prod", { expect_equal(length(e.value.student.t.next.k$e.value.alt.more.cons.prod), 1) })
test_that("e_value sequential work as expected for random distribution - e.value.alt.more.cons.prod - type", { expect_type(e.value.student.t.next.k$e.value.alt.more.cons.prod, "double") })

### testing with a different scoring function
n.obs <- 10
mu <- rnorm(n.obs)
new.mu <- rnorm(1)
logs.F.para <- list("mu" = mu, "sd" = 1, "main" = TRUE, "method" = 'norm', "fun" = \(y) {scoringRules::logs_norm(y = y, mean = mu, sd = 1)}, "sample.fun" = \(n, n.obs) {matrix(rnorm(n * n.obs, mean = mu, sd = 1), nrow = n.obs)}, "inf.fun" = \(x,j) {scoringRules::logs_norm(y = x, mean = mu[j], sd = 1)})
logs.G.para <- list("mu" = mu + 0.01,  "sd" = 1, "method" = 'norm', "fun" = \(y) {scoringRules::logs_norm(y = y, mean =  mu + 0.01,  sd = 1)}, "sample.fun" = \(n, n.obs) {matrix(rnorm(n * n.obs, mean = mu + 0.01,  sd = 1), nrow = n.obs)}, "inf.fun" = \(x, j) {scoringRules::logs_norm(y = x, mean =  mu[j] + 0.01, sd = 1)} )
e.value.log.score <- e_value(y = stats::rnorm(n.obs), crps.F.para = logs.F.para, crps.G.para = logs.G.para, method = c("alt-cons","GRAPA", "lambda", "alt-conf", "alt-more-cons"), p.value.method = "t")
e.value.log.score.next.k <- e_value(old.run.e.value = e.value.log.score, new.y = stats::rnorm(1, new.mu), new.crps.F.para = list("mu" = new.mu, "sd" = NA), new.crps.G.para = list("mu" = new.mu + 0.01, "sd" = NA))
test_that("e_value sequential work as expected for log score - dim crps.alt.cons", { expect_equal(dim(e.value.log.score.next.k$crps.alt.cons), c(11, 50)) })
test_that("e_value sequential work as expected for log score - length y", { expect_equal(length(e.value.log.score.next.k$y), 11) })
test_that("e_value sequential work as expected for log score - crps.F length", { expect_equal(length(e.value.log.score.next.k$crps.F), 11) })
test_that("e_value sequential work as expected for log score - crps.F.para length", { expect_equal(length(e.value.log.score.next.k$crps.F.para), 7) })
test_that("e_value sequential work as expected for log score - crps.F.para - length mu", { expect_equal(length(e.value.log.score.next.k$crps.F.para$mu), 11) })
test_that("e_value sequential work as expected for log score - crps.F.para - length sd", { expect_equal(length(e.value.log.score.next.k$crps.F.para$sd), 1) })
test_that("e_value sequential work as expected for log score - crps.F.para types - fun", { expect_type(e.value.log.score.next.k$crps.F.para$fun, "closure") })
test_that("e_value sequential work as expected for log score - crps.F.para types - crps.fun.y.matrix", { expect_type(e.value.log.score.next.k$crps.F.para$crps.fun.y.matrix, "closure") })
test_that("e_value sequential work as expected for log score - crps.F.para types - sample.fun", { expect_type(e.value.log.score.next.k$crps.F.para$sample.fun, "closure") })
test_that("e_value sequential work as expected for log score - crps.F.para types - inf.fun", { expect_type(e.value.log.score.next.k$crps.F.para$inf.fun, "closure") })
test_that("e_value sequential work as expected for log score - crps.F.para - method", { expect_equal(e.value.log.score.next.k$crps.F.para$method, "norm") })
test_that("e_value sequential work as expected for log score - crps.G.para length", { expect_equal(length(e.value.log.score.next.k$crps.G.para), 7) })
test_that("e_value sequential work as expected for log score - crps.G length", { expect_equal(length(e.value.log.score.next.k$crps.G), 11) })
test_that("e_value sequential work as expected for log score - crps.G.para - length mu", { expect_equal(length(e.value.log.score.next.k$crps.G.para$mu), 11) })
test_that("e_value sequential work as expected for log score - crps.G.para - length sd", { expect_equal(length(e.value.log.score.next.k$crps.G.para$sd), 1) })
test_that("e_value sequential work as expected for log score - crps.G.para types - fun", { expect_type(e.value.log.score.next.k$crps.G.para$fun, "closure") })
test_that("e_value sequential work as expected for log score - crps.G.para types - crps.fun.y.matrix", { expect_type(e.value.log.score.next.k$crps.G.para$crps.fun.y.matrix, "closure") })
test_that("e_value sequential work as expected for log score - crps.G.para types - sample.fun", { expect_type(e.value.log.score.next.k$crps.G.para$sample.fun, "closure") })
test_that("e_value sequential work as expected for log score - crps.G.para types - inf.fun", { expect_type(e.value.log.score.next.k$crps.G.para$inf.fun, "closure") })
test_that("e_value sequential work as expected for log score - crps.G.para - method", { expect_equal(e.value.log.score.next.k$crps.G.para$method, "norm") })
test_that("e_value sequential work as expected for log score - inf.crps type", { expect_type(e.value.log.score.next.k$inf.crps, "double") })
test_that("e_value sequential work as expected for log score - method", { expect_equal(e.value.log.score.next.k$method, c("alt-cons","GRAPA", "lambda", "alt-conf", "alt-more-cons")) })
test_that("e_value sequential work as expected for log score - p.value.method", { expect_equal(e.value.log.score.next.k$p.value.method, "t") })
test_that("e_value sequential work as expected for log score - p.value", { expect_equal(length(e.value.log.score.next.k$p.value), 1) })
test_that("e_value sequential work as expected for log score - crps.alt.cons", { expect_equal(dim(e.value.log.score.next.k$crps.alt.cons), c(11, 50)) })
test_that("e_value sequential work as expected for log score - e.value.alt.cons", { expect_equal(length(e.value.log.score.next.k$e.value.alt.cons), 11) })
test_that("e_value sequential work as expected for log score - lambda.alt.cons", { expect_equal(length(e.value.log.score.next.k$lambda.alt.cons), 11) })
test_that("e_value sequential work as expected for log score - e.value.alt.cons.prod", { expect_equal(length(e.value.log.score.next.k$e.value.alt.cons.prod), 1) })
test_that("e_value sequential work as expected for log score - e.value.alt.cons.prod - type", { expect_type(e.value.log.score.next.k$e.value.alt.cons.prod, "double") })
test_that("e_value sequential work as expected for log score - crps.alt.conf", { expect_true(is.matrix(e.value.log.score.next.k$crps.alt.conf)) })
test_that("e_value sequential work as expected for log score - e.value.alt.conf", { expect_equal(length(e.value.log.score.next.k$e.value.alt.conf), 11) })
test_that("e_value sequential work as expected for log score - lambda.alt.conf", { expect_equal(length(e.value.log.score.next.k$lambda.alt.conf), 11) })
test_that("e_value sequential work as expected for log score - e.value.alt.conf.prod", { expect_equal(length(e.value.log.score.next.k$e.value.alt.conf.prod), 1) })
test_that("e_value sequential work as expected for log score - e.value.alt.conf.prod - type", { expect_type(e.value.log.score.next.k$e.value.alt.conf.prod, "double") })
test_that("e_value sequential work as expected for log score - crps.alt.more.cons", { expect_true(is.matrix(e.value.log.score.next.k$crps.alt.more.cons)) })
test_that("e_value sequential work as expected for log score - e.value.alt.more.cons", { expect_equal(length(e.value.log.score.next.k$e.value.alt.more.cons), 11) })
test_that("e_value sequential work as expected for log score - lambda.alt.more.cons", { expect_equal(length(e.value.log.score.next.k$lambda.alt.more.cons), 11) })
test_that("e_value sequential work as expected for log score - e.value.alt.more.cons.prod", { expect_equal(length(e.value.log.score.next.k$e.value.alt.more.cons.prod), 1) })
test_that("e_value sequential work as expected for log score - e.value.alt.more.cons.prod - type", { expect_type(e.value.log.score.next.k$e.value.alt.more.cons.prod, "double") })